# This is a basic workflow to help you get started with Actions

name: Build a ZIP package that can be directly uploaded to Hackathon system

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8
          
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Install dependencies
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Start building the package
        run: poetry run python3 main.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: zip package
          # A file, directory or wildcard pattern that describes what to upload
          path: ./package.zip
          # The desired behavior if no files are found using the provided path.
